In [1]:
from pathlib import Path

import pandas as pd
import numpy as np
import csv

In [2]:
try:
    import common
    DATA = common.dataDirectory()
except ImportError:
    DATA = Path().resolve() / 'data'

In [149]:
for entry in DATA.iterdir():
    if entry.is_file():
        print(entry.name)

hw6_init_matrix.csv
hw6_inv_matrix.csv
interv_mat.csv
hw6_fd_q2.csv
hw6_fd_q5.csv
hw6_tech_matrix.csv


In [150]:
techMat_csv = DATA / 'hw6_tech_matrix.csv'
fdQ2_csv = DATA / 'hw6_fd_q2.csv'
fdQ5_csv = DATA / 'hw6_fd_q5.csv'
intervMat_csv= DATA / 'interv_mat.csv'

In [151]:
ncols = 43
def tech_matrix(fileName):
    '''
    tech_matrix function is used to convert csv into matrix for technology matrix.
    '''
    fill_val = 0
    fileName = np.genfromtxt(fileName, delimiter=',', usecols=np.arange(2,ncols), filling_values=fill_val,skip_header=True)
    print('The matrix conversion is completed')
    print(f'The matrix shape is: {fileName.shape}')
    return fileName

In [152]:
t_mat=tech_matrix(techMat_csv)

The matrix conversion is completed
The matrix shape is: (41, 41)


In [153]:
t_mat.dtype

dtype('float64')

In [154]:
def tech_matrix_inv(technology_matrix):
    '''
    tech_matrix_inv is a function to inverse the technology matrix
    for next processes.
    '''
    technology_matrix = np.linalg.inv(technology_matrix)
    return technology_matrix

In [155]:
t_mat_inv = tech_matrix_inv(t_mat)
t_mat_inv

array([[ 1.00000000e+00,  0.00000000e+00,  0.00000000e+00, ...,
         0.00000000e+00,  0.00000000e+00,  0.00000000e+00],
       [-0.00000000e+00, -2.33814211e+02, -7.55314510e+16, ...,
        -1.91781146e+26, -0.00000000e+00,  4.33007062e+23],
       [-0.00000000e+00, -0.00000000e+00,  1.33390565e-01, ...,
         1.06829235e+06, -0.00000000e+00, -2.53205704e+03],
       ...,
       [-0.00000000e+00, -0.00000000e+00,  2.80444996e-02, ...,
        -1.65004138e+07, -8.23723229e+01,  3.72576093e+04],
       [-0.00000000e+00, -0.00000000e+00,  3.40460225e-04, ...,
        -2.00315023e+05, -0.00000000e+00,  4.52307378e+02],
       [ 0.00000000e+00,  0.00000000e+00,  1.25917494e-26, ...,
         9.74239425e-01,  0.00000000e+00,  5.81660016e-05]])

In [156]:
t_mat_inv.shape[0]

41

In [157]:
technology_matrix_inv = t_mat_inv
nrows = technology_matrix_inv.shape[0]
fdemand_val = 1
fdemand_mat = np.array([fdemand_val])

In [158]:
def create_fdemand_matrix(fdemand_val, nrows):
    '''
    create_fdemand_matrix is a function to create final demand matrix;
    ARGUMENTS:
        fdemand_val = value of final demand;
        nrows = number of rows, can be taken from the technology matrix m-dimension
        
    '''
    fdemand_matrix = np.zeros((nrows-1,1))
    fdemand_matrix = np.vstack([fdemand_mat, fdemand_matrix])
    return fdemand_matrix

In [159]:
fdemand_matrix = create_fdemand_matrix(1, nrows)
fdemand_matrix.dtype

dtype('float64')

In [166]:
# Alternative function, if we have already make fdemand csv file
def fdemand_matrix(fileName):
    fill_val = 0
    fileName=np.genfromtxt(fileName, delimiter=',',skip_header=True)
    print('The matrix conversion is completed')
    print(f'The matrix shape is: {fileName.shape}')
    return fileName.reshape(fileName.shape[0],1)
    print(f'The matrix shape is: {fileName.shape}')

In [167]:
fdemand_matrix(fdQ2_csv)

The matrix conversion is completed
The matrix shape is: (41,)


array([[1.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.]])

In [23]:
techMat_inv = np.linalg.inv(techMat)
techMat_inv

array([[ 1.00000000e+00,  0.00000000e+00,  0.00000000e+00, ...,
         0.00000000e+00,  0.00000000e+00,  0.00000000e+00],
       [-0.00000000e+00, -2.33814211e+02, -7.55314510e+16, ...,
        -1.91781146e+26, -0.00000000e+00,  4.33007062e+23],
       [-0.00000000e+00, -0.00000000e+00,  1.33390565e-01, ...,
         1.06829235e+06, -0.00000000e+00, -2.53205704e+03],
       ...,
       [-0.00000000e+00, -0.00000000e+00,  2.80444996e-02, ...,
        -1.65004138e+07, -8.23723229e+01,  3.72576093e+04],
       [-0.00000000e+00, -0.00000000e+00,  3.40460225e-04, ...,
        -2.00315023e+05, -0.00000000e+00,  4.52307378e+02],
       [ 0.00000000e+00,  0.00000000e+00,  1.25917494e-26, ...,
         9.74239425e-01,  0.00000000e+00,  5.81660016e-05]])

In [172]:
def calc_emission(technology_matrix, final_demand, intervention_matrix):
    '''
    calc_emission
    is used to calculate the emission from matrix.
    It takes three inputs, namely:
                        1) technology_matrix;
                        2) final_demand;
                        3) intervention_matrix
    '''
    technology_matrix_inv = np.linalg.inv(technology_matrix)
    scale_matrix = np.dot(technology_matrix_inv, final_demand)
    result_matrix = np.dot(intervention_matrix, scale_matrix)
    print (result_matrix)

In [173]:
intervMat = pd.read_csv(intervMat_csv)
intervMat = pd.DataFrame(intervMat).fillna(0)
intervMat = intervMat.apply(pd.to_numeric, errors='coerce').dropna(axis='columns').to_numpy(dtype=float,na_value=0)

In [174]:
intervMat.shape

(3, 41)

In [178]:
t_mat

array([[ 1.0000e+00,  0.0000e+00,  0.0000e+00, ...,  0.0000e+00,
         0.0000e+00,  0.0000e+00],
       [ 0.0000e+00, -4.2769e-03,  2.5230e-01, ...,  0.0000e+00,
         0.0000e+00,  0.0000e+00],
       [ 0.0000e+00,  0.0000e+00, -1.3340e-03, ...,  0.0000e+00,
         0.0000e+00,  0.0000e+00],
       ...,
       [ 0.0000e+00,  0.0000e+00,  0.0000e+00, ...,  0.0000e+00,
         0.0000e+00,  1.0000e+00],
       [ 0.0000e+00,  0.0000e+00,  0.0000e+00, ..., -1.2140e-02,
         1.0000e+00,  0.0000e+00],
       [ 0.0000e+00,  0.0000e+00,  0.0000e+00, ...,  0.0000e+00,
         0.0000e+00, -2.0600e+01]])

In [175]:
calc_emission(t_mat, fdemand_matrix, intervMat)

TypeError: unsupported operand type(s) for *: 'float' and 'function'

# Important!!
There is still error somewhere in the technology matrix creation; not yet solved, but the calc_emission and calc_emission_v2 should be priorities.